# Generated by Django 2.0.6 on 2018-06-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaruser',
            name='is_interviewer',
            field=models.BooleanField(help_text="Boolean, accepting values 'true' or 'false'. True if user is an interviewer, false if user is a candidate"),
        ),
    ]
