# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-20 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('time_slots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarusertimeslot',
            name='calendar_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CalendarUser'),
        ),
    ]
