# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-20 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('time_slots', '0002_calendarusertimeslot_calendar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendartimeslot',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='calendartimeslot',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='calendartimeslot',
            name='start_hour',
        ),
        migrations.AddField(
            model_name='calendartimeslot',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendartimeslot',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
