# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-21 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('time_slots', '0005_auto_20180620_2003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendarusertimeslot',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='calendarusertimeslot',
            name='calendar_time_slot',
        ),
        migrations.RemoveField(
            model_name='calendarusertimeslot',
            name='calendar_user',
        ),
        migrations.AddField(
            model_name='calendartimeslot',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.CalendarUser'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CalendarUserTimeSlot',
        ),
    ]
