# Generated by Django 2.0.6 on 2018-06-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_slots', '0007_auto_20180623_0924'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendartimeslot',
            unique_together=set(),
        ),
    ]
